_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 13
                - 16
                - 55
            "4": 3.8.20
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 4
beta_end:
    value: 48
beta_start:
    value: 8
boosting_update_epoch_freq:
    value: 5
checkpoint_dir:
    value: /home/ha51dybi/PEBAL/code/checkpoints_pixel_wise_final
id_memory_size:
    value: 2000
lambda_ood:
    value: 0.3
learning_rate:
    value: 0.001
max_pixel_pool_size:
    value: 50000
model_path:
    value: /home/ha51dybi/PEBAL/code/ckpts/pretrained_ckpts/cityscapes_best.pth
num_classes:
    value: 19
ood_memory_size:
    value: 1000
pixel_beta_border_static:
    value: 32
pixel_beta_inference:
    value: 64
pixel_beta_sampling:
    value: 16
projection_dim:
    value: 128
resize_resolution:
    value:
        - 256
        - 256
total_epochs:
    value: 50
use_beta_scheduling:
    value: true
weight_decay:
    value: 0.0001
