_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 2
                - 13
                - 16
                - 55
                - 61
            "4": 3.8.20
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 2
beta_border:
    value: 8
beta_sampling:
    value: 8
boosting_update_epoch_freq:
    value: 5
boosting_warmup_epochs:
    value: 5
boosting_warmup_freq:
    value: 2
id_memory_size:
    value: 3000
lambda_ood:
    value: 0.5
learning_rate:
    value: 0.0005
max_pixel_pool_size:
    value: 50000
model_path:
    value: /home/ha51dybi/PEBAL/code/ckpts/pretrained_ckpts/cityscapes_best.pth
num_classes:
    value: 19
num_hard_pixels_per_batch:
    value: 1024
ood_memory_size:
    value: 1500
projection_dim:
    value: 128
total_epochs:
    value: 30
weight_decay:
    value: 0.0005
