_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 13
                - 16
                - 55
            "4": 3.8.20
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 2
beta_border:
    value: 128
beta_sampling:
    value: 128
lambda_ood:
    value: 1
learning_rate:
    value: 0.1
max_aux_samples_for_weight_update:
    value: 50000
model_path:
    value: /home/ha51dybi/PEBAL/code/ckpts/pretrained_ckpts/cityscapes_best.pth
num_classes:
    value: 19
proj_hidden_dim:
    value: 256
projection_dim:
    value: 128
sampled_memory_size:
    value: 2000
total_iterations:
    value: 10000
weight_decay:
    value: 0.0005
weight_update_frequency:
    value: 100
