_wandb:
    value:
        cli_version: 0.20.1
        code_path: source-hopfield-boosting-ood-detection-code_run_training.py
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 1
                - 13
                - 16
                - 55
                - 62
            "4": 3.8.20
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
aux_memory_size:
    value: 50000
batch_size:
    value: 4
beta:
    value: 32
dataset:
    value: Cityscapes+COCO
id_memory_size:
    value: 50000
lambda_ood:
    value: 2
learning_rate:
    value: 0.1
model:
    value: PixelWiseHopfield
projection_dim:
    value: 128
total_epochs:
    value: 100
weight_decay:
    value: 0.0005
